### ISSUE TITLE
If the End Date is not set, the Item is showing it as "Place Holder"

### ISSUE THREAD

**Issue by sandy99405** [Rd4dev/Habit-Tracker#3]
The Item Holder is showing "Place Holder" if the End Date is not set while creating a new task. 

It would be better if it's "FOREVER" or "NO END DATE"

![Screenshot_20240116_090851_Habit-Tracker](https://github.com/Rd4dev/Habit-Tracker/assets/55664068/168c1a19-81fe-458d-bd0a-49215987cad5)

**Comment by Rd4dev** [comment]
Solved via #4

**Comment by Rd4dev** [comment]
Thanks @sandy99405
